openhabdata:
  image: sdhibit/rpi-openhab:latest
  command: /bin/true

openhab:
  image: sdhibit/rpi-openhab:latest
  volumes_from:
   - openhabdata
  ports:
   - "8080:8080"
   - "8443:8443"
   - "5555:5555"
  restart: always
  
